CREATE TABLE IF NOT EXISTS  `accounts`
(
    id int GENERATED BY DEFAULT AS IDENTITY(START
        WITH 10000) PRIMARY KEY,
    account_number int not null,
    pin_number     int not null,
    balance       FLOAT,
    login_attempts int  default '3',
    active         BOOL default false,
    primary key (id)
);
CREATE TABLE IF NOT EXISTS `customers`
(
    id         int         NOT NULL AUTO_INCREMENT,
    first_name varchar(30) not null,
    last_name  varchar(30) not null,
    account_id int         not null,
    password   varchar(30) not null,
    primary key (id),
    FOREIGN KEY (account_id)
        REFERENCES `accounts` (id)
);
CREATE TABLE IF NOT EXISTS `transactions`
(
    id               int         NOT NULL AUTO_INCREMENT,
    transaction_type varchar(20) not null,
    amount           FLOAT       not null,
    account_id       int default null,
    date             DATETIME    not null,
    description      varchar(64) not null,
    primary key (id),
    FOREIGN KEY (account_id)
        REFERENCES `accounts` (id)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);
INSERT INTO `accounts` VALUES(10,200,2000,200,3,1);
INSERT INTO `accounts` VALUES(11,201,2000,200,3,1);
INSERT INTO `customers` VALUES(10,'USER1','USERNAME1',10,'1234');
INSERT INTO `customers` VALUES(11,'USER2','USERNAME2',11,'1234');
